#!/bin/bash

LOCKFILE=/var/lock/cronsync.lock

SOURCEDIR=/mnt/source/
DESTDIR=/mnt/raid/

LOGFILE=/var/log/cronsync.log

if [ ! -f $LOCKFILE ]; then
	touch $LOCKFILE
fi

if mountpoint -q $SOURCEDIR && mountpoint -q $DESTDIR; then
	flock -n $LOCKFILE -c "rsync -av --delete-after $SOURCEDIR $DESTDIR >> $LOGFILE 2>&1"
else
	echo "$SOURCEDIR or $DESTDIR not mounted!"
	exit 251
fi


	


