#!/bin/bash

LOCKFILE=/var/lock/cronsync.lock

SOURCEDIR="$1"
DESTDIR="$2"

LOGFILE=/var/log/cronsync.log

if [ ! -f $LOCKFILE ]; then
        touch $LOCKFILE
fi

echo "##########################################" >> $LOGFILE
date >> $LOGFILE

if [ -d  $SOURCEDIR ] && [ -d $DESTDIR ]; then
        flock -n $LOCKFILE -c "rsync -aAXv --delete-after $SOURCEDIR $DESTDIR >> $LOGFILE 2>&1"
else
        echo "$SOURCEDIR or $DESTDIR not mounted!"
        exit 251
fi
